# Python 3.6 et Numpy in 20 minutes
yann chevaleyre

## Python en 5 minutes

Contrairement au langages C,C++ et Java, il n'y a pas d'accolade ouvrante ou fermante en python pour les blocs if,while,etc...
En python, le symbole ':' signale qu'on rentre dans un nouveau bloc d'instruction. Ce bloc doit etre indente par une tabulation ou par 4 espaces.

In [1]:
# Ces trois codes font exactement la meme chose

print('\n Premier code')

x = 0
while x < 4:
    print ('iteration ',x)
    x += 1


print('\n Deuxieme code')

for x in range(4):
    print ('iteration ',x)


print('\n Troisieme code')

def foo(x):
    while True:
        if x >= 4:
            break
        else:
            print ('iteration ',x)
            x = x + 1
foo(0)


 Premier code
iteration  0
iteration  1
iteration  2
iteration  3

 Deuxieme code
iteration  0
iteration  1
iteration  2
iteration  3

 Troisieme code
iteration  0
iteration  1
iteration  2
iteration  3


In [13]:
# Exercice !
# Ecrire une fonction renvoie la somme des nombres de 1 a x

def sum(x) :
    tmp = x
    res = 0
    while (tmp >= 0) :
        res += tmp
        tmp = tmp - 1
    return res

def lazysum(x):
    x =(x*(x+1))/2
    return x
    
lazysum(5)
sum(5)

15

In [14]:
# En python, on manipule beaucoup des listes.
# Dans les listes, on met ce qu'on veut (des chaines de caracteres, des nombres)
L = ['A','B','C']
N = [10,15,20]
print(L+N)
print(L[0],";",N[1])

['A', 'B', 'C', 10, 15, 20]
A ; 15


In [15]:
# En python, enormement de choses se trouvent dans les modules externes
# on les appelle avec import est on leur donne un nom raccourci

import random
R = random.choice(['A','B','C'])
print('Parmi A,B ou C, je choisis aleatoirement ',R)

import math as m
print ('racine de deux egal ',m.sqrt(2))
print ('cosinus de pi egal',m.cos( m.pi ))

Parmi A,B ou C, je choisis aleatoirement  C
racine de deux egal  1.4142135623730951
cosinus de pi egal -1.0


In [ ]:
# Je peux aussi definir des fonctions avec def
# ici je definis normeVec qui calcule la norme d'un vecteur
def normeVec(x,y):
    return m.sqrt(x*x+y*y)

print ('norme du vecteur (10,20) = ',normeVec(10,20))

## Numpy en 10 minutes
Numpy est le module python qui permet de manipuler des matrices (entres autres). Ca ressemble beaucoup a Matlab

In [16]:
# Le module qui permet de manipuler des matrices s'appelle numpy, mais on abbregera par np

import numpy as np

x = np.array( [ [1,2,3] , [10,20,30] ] )
print (' voila la matrice x :')
print (x)

w = np.zeros( (3,4) )
print ('\n voila la matrice w :')
print (w)

v = np.ones( (1,10) )
print ('\n voila la matrice v :')
print (v)

identite = np.eye( 3 )
print ('\n voila la matrice identite :')
print (identite)



 voila la matrice x :
[[ 1  2  3]
 [10 20 30]]

 voila la matrice w :
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

 voila la matrice v :
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 voila la matrice identite :
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [17]:
# on peut obtenir la dimension d'une matrice x avec x.shape,
# on peut transposer une matrice x avec x.T

print (' dimension de la matrice avant transposition ',x.shape)

print ('\n voici la matrice transposee:')
x = x.T
print (x)

print ('\n et ses nouvelles dimensions: ',x.shape)
print (' elle a donc ',x.shape[0],' lignes et ',x.shape[1],' colonnes')

 dimension de la matrice avant transposition  (2, 3)

 voici la matrice transposee:
[[ 1 10]
 [ 2 20]
 [ 3 30]]

 et ses nouvelles dimensions:  (3, 2)
 elle a donc  3  lignes et  2  colonnes


In [ ]:
# On peut extraire des morceaux d'une matrice x avec x[i1:i2,j1:j2]
# ca prend les lignes de i1 a i2-1, et j1 a j2-1
# lignes et colonnes sont numerotes a partir de zero

print (' extraction des lignes de 0 a 1 et colonnes de 0 a 1')
print (x[0:2,0:2])

print ('\n extraction de toutes les lignes de x, mais juste la seconde colonne')
z = x[:,1:2]
print (z)

print ('\n extraction de la premier ligne de x avec toutes les colonnes')
z2 = x[0,:]
print (z2)

In [ ]:
print('acceder aux valeurs des cases de la matrice une par une')
x[0,0] = 1000
print (x)

In [ ]:
print('parcourir un tableau numpy en deux dimensions, avec double boucle for')
for i in range(len(x)):
    for j in range(len(x[0])):
        e = x[i,j]
        print("l'element a la ligne",i,"et la colonne",j,"est",e)

print('\nparcourir un tableau numpy en deux dimensions, avec une seule boucle for')
for (i,j),e in np.ndenumerate(x):
        print("l'element a la ligne",i,"et la colonne",j,"est",e)

In [33]:
# Exercice !
# Ecrire une fonction qui cree une matrice 5x5 initialement remplie de zeros.
# Puis, pour i=1..5 et j=1..5, placer dans la case i,j de cette matrice la valeur min(i,j)

zero = np.zeros( (5,5) )
for i in range(len(zero)):
    for j in range(len(zero)):
        zero[i,j] = min(i,j)
  
#v2 

for (i,j),e in np.ndenumerate(x):
    zero[i,j] = min(i,j)
        
print(zero)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.]
 [ 0.  1.  2.  2.  2.]
 [ 0.  1.  2.  3.  3.]
 [ 0.  1.  2.  3.  4.]]


In [32]:
# multiplications et produits scalaires

v = np.array( [ [10,20,30] ])

print (' v est une matrice ligne ')
print (v)

print ('\n sa transposee est une matrice colonne ')
print (v.T)

print ("\n le resultat de v * v.T est une matrice 1x1, et s'ecrit de deux facons equivalentes")
print (np.dot( v , v.T))
print (' ou en utilisant le symbole de multiplication matriciel "@"')
print ( v @ v.T)

print ('\n on peut extraire le nombre en convertissant un reel')
print (float( v @ v.T ))

print ('\n le resultat de v.T * v est une matrice 3x3')
print ( v.T @ v)


 v est une matrice ligne 
[[10 20 30]]

 sa transposee est une matrice colonne 
[[10]
 [20]
 [30]]

 le resultat de v * v.T est une matrice 1x1, et s'ecrit de deux facons equivalentes
[[1400]]
 ou en utilisant le symbole de multiplication matriciel "@"
[[1400]]

 on peut extraire le nombre en convertissant un reel
1400.0

 le resultat de v.T * v est une matrice 3x3
[[100 200 300]
 [200 400 600]
 [300 600 900]]


In [ ]:
#  on peut faire plein de choses sur des matrices

print ('\n on peut multiplier v par un nombre:')
print (v*1000)

print ('\n appliquer une operation sur chaque element (elever au carre, calculer la racine carre, le log) de v')
print (v**2)
print (np.sqrt(v))
print (np.log(v))

print ('\n ajouter v a v')
print (v+v)

print ('\n contatener horizontalement et verticalement v a lui-meme')
print (np.hstack( (v,v) ))
print (np.vstack( (v,v) ))

print ('\n faire la somme en lignes de la matrice x:')
print (x)
print (' somme sur les ligne = ',np.sum(x,axis=0))
print (' somme sur les colonne = \n',np.sum(x,axis=1))

print ('\n generer des matrices aleatoires')
al = np.random.uniform(size=(2,4))
# Attention: np.random.uniform peut generer des tableaux 1D, 2D, 3D... mais pas de matrices.
# Donc ici, np.random.uniform genere un tableau 2D qu'on converti explicitement en matrice avec np.matrix(...)
print (al)

In [77]:
# Exercice !
# Reprenez la matrice de l'exercice precedent
# Rajoutez une colonne de 1 a cette matrice.



v = v.T
vv = np.array( [ [1,1,1] ]).T

print (np.hstack( (vv,v) ))




[[ 1 10]
 [ 1 20]
 [ 1 30]]


In [74]:
# Exercice !
# Centrez cette matrice, c'est a dire soustrayez a chaque colonne la moyenne de cette colonne.
# Pour cela, il faudra entre autres utiliser la fonction np.mean
# pour acceder a l'aide de cette fonction, tapez help(np.mean) ou np.mean?

In [72]:
print("changer la forme d'un tableau ou d'une matrice")
X = np.array([1,2,3,4,5,6])  # X est un tableau 1D
print(X)
X = X.reshape(1,6)           # X est maintenant un tableau 2D
print(X)
X = X.reshape(6,1)
print(X)
X = X.reshape(2,3)
print(X)

changer la forme d'un tableau ou d'une matrice
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]


## Matplotlib
matplotlib est le module qui permet d'afficher des graphiques. Lui aussi s'utilise presque comme Matlab

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
v = np.array([[1,3,2,4,3,5,4,6]])
plt.plot(v.T)  # Attention, plt.plot requiert des matrices colonnes. il faut donc transposer v
plt.show()     # affiche le graphique

In [ ]:
# Afficher des points connaissant leurs coordonnes
x = np.array([[10,20,15,33]])
y = np.array([[1,2,3,6]])
plt.scatter(x.T,y.T)
plt.show()

## Charger les données Iris

In [ ]:
from sklearn.datasets import load_iris
X , y = load_iris().data, load_iris().target

print(X[:4],'\n\n',y[:4])

In [ ]:
# Exercice !
# Affichez graphiquement avec plt.scatter les deux premieres colonnes du jeu de donnees iris

## Comparaisons sur des tableaux numpy

On peut faire des comparaisons entre tableaux et nombres de la facon suivante

In [ ]:
X = np.arange(25)
X

In [ ]:
Y = X > 10
Y

In [ ]:
# on peut convertir le tableau de booleens en tableau d'entiers
Z = Y.astype(int)
Z

In [39]:
# Exercice !
# créez un matrice X de nombres réels aléatoires tirés uniformément entre 0 et 1,
# et creez une matrice Y ne contenant que des -1 et des 1 de la facon suivante:
# si X[i,j] > 0.5 alors la case Y[i,j] devra prendre la valeur 1, et -1 sinon.
# bien sur, n'utilisez pas de boucle for dans cet exercice